# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], verbose_name='性别')),
                ('birthdate', models.DateField(verbose_name='出生日期')),
                ('studentID', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('school', models.CharField(max_length=100, verbose_name='在读学校')),
                ('major', models.CharField(max_length=100, verbose_name='在读专业')),
                ('admission', models.DateField(verbose_name='入学时间')),
                ('gpa', models.FloatField(verbose_name='成绩')),
                ('mobile', models.IntegerField(verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
                ('friends', models.ManyToManyField(related_name='_student_friends_+', to='study.Student', verbose_name='好友')),
            ],
        ),
    ]
