# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.DateField(null=True, verbose_name='入学时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_student_friends_+', to='study.Student', verbose_name='好友'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(null=True, verbose_name='成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100, null=True, verbose_name='在读专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=100, null=True, verbose_name='在读学校'),
        ),
    ]
