# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20161117_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(related_name='_student_friends_+', to='study.Student', verbose_name='好友'),
        ),
    ]
