# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': '家庭成员', 'verbose_name_plural': '家庭成员'},
        ),
        migrations.AlterField(
            model_name='parent',
            name='relation',
            field=models.CharField(blank=True, choices=[('f', '父亲'), ('m', '母亲'), ('o', '其他')], max_length=10, null=True, verbose_name='关系'),
        ),
    ]
